### ISSUE TITLE
Finalizing User Story

### ISSUE THREAD

**Issue by FrankeyDee** [Spacejnk/ApiProject#4]
@Spacejnk
Hello....

**Comment by Spacejnk** [comment]
@czjordan323 @FrankeyDee 
Hey, have we figured this project out yet?

**Comment by czjordan323** [comment]
@Spacejnk @FrankeyDee 

**User Story** - The user will be able to search for restaurants  in a specific area and be able to see the most recent trending comments/post regarding the restaurants of the users choice.

Feel free to add to this story

**Comment by FrankeyDee** [comment]
commenting # @

- [ ]

**Comment by FrankeyDee** [comment]
testing reopening

**Comment by czjordan323** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SUMMARY](https://trello.com/c/G8xJ28id/11-summary)
